### ISSUE TITLE
Create two resolved categories Degraded-Resolved alerts and Activated-Resolved Alerts

### ISSUE THREAD

**Issue by Nicki-Susman** [checkly/product-roadmap#53]
We need two different resolved options in the alerting settings. With the introduction of degraded alerts, having a single generic resolved alert no longer makes sense. We need one for an activated alert resolved, and another for a degraded alert resolved. Use case - our product owners only subscribe to activated alerts - not degraded alerts - so they're going to be very confused getting a resolved alert when they never received an activated alert.

**Comment by tnolet** [comment]
We just exposed the ALERT_DEGRADED_RECOVERY status in webhooks and updated the docs to reflect this. https://checklyhq.com/docs/alerting/webhooks/

This means you can separately track the resolving of checks in a degraded status. 

Fun fact: it was one line of code! We "hide" some internal alert types from the webhook integration because they are used only for internal alerting plumbing. 

```
function mapAlertType (alertType) {
  switch (alertType) {
    case alertTypes.ALERT_FAILURE:
    case alertTypes.ALERT_FAILURE_REMAIN:
    case alertTypes.ALERT_DEGRADED_FAILURE:
      return alertTypes.ALERT_FAILURE
    case alertTypes.ALERT_DEGRADED:
      return alertTypes.ALERT_DEGRADED
    case alertTypes.ALERT_RECOVERY:
      return alertTypes.ALERT_RECOVERY
    case alertTypes.ALERT_DEGRADED_RECOVERY:
      return alertTypes.ALERT_DEGRADED_RECOVERY // we added this line
    default:
      return alertTypes.NO_ALERT
  }
}
```
